name = "ProbabilityThing"
uuid = "d569a39a-dfd6-437e-9042-ffa40528d8ad"
authors = ["Olga Lyashevska <olga@herenstraat.nl> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
